# Generated by Django 2.2 on 2020-03-15 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaType', models.CharField(max_length=100)),
                ('pizzaName', models.CharField(max_length=100)),
                ('pizzaSize', models.CharField(max_length=100)),
                ('toppings', models.CharField(max_length=100)),
                ('contactName', models.CharField(max_length=100)),
                ('contactNumber', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 15, 15, 48, 57, 9408))),
                ('status', models.CharField(default='pizza in the kitchen yet!', max_length=100)),
            ],
        ),
    ]
